name: Jellyfin Docker Image Publish

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest version of jellyfin
      id: getVersion
      run: |
        version=$(apk info --no-cache jellyfin | grep 'jellyfin' | awk '{print $1}' | awk 'NR==1' | awk -F "-" '{print $2}')
        echo "curentVersion=$version" >> $GITHUB_OUTPUT
      shell: alpine.sh {0}
     
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to AliYun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER }}
        password: ${{ secrets.ALIYUN_TOKEN }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        context: .
        push: true
        tags: |
          clion007/jellyfin:latest
          clion007/jellyfin:${{ steps.getVersion.outputs.curentVersion }}
          registry.cn-chengdu.aliyuncs.com/clion/jellyfin:latest
          registry.cn-chengdu.aliyuncs.com/clion/jellyfin:${{ steps.getVersion.outputs.curentVersion }}
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
